### ISSUE TITLE
Add accepts non-youtube link

### ISSUE THREAD

**Issue by villheik** [jkarppinen/korvamato#1]
Current behaviour:
When adding a new link, "https://yout.com/" gets through and is added to shuffle

Expected behaviour:
"https://yout.com/" should be rejected as it is not an youtube link

It seems like the string parser on line 33 is not sufficient enough to eliminate all non-youtube links

**Comment by jkarppinen** [comment]
Thank you for reporting this! The idea behind the logic in line 33 is to accept links from youtube.com and youtu.be URLs. Pull requests very welcome.

**Comment by jhyvonen** [comment]
Current implementation also allows for plain youtube.com links, without having a video ID attached. I'm working on a fix for this.

**Comment by jhyvonen** [comment]
Created pull request to fix this issue:
https://github.com/jkarppinen/korvamato/pull/2

**Comment by jkarppinen** [comment]
Great, thanks! Reviewed & merged 🎉
